### ISSUE TITLE
Sensors etc. not being created

### ISSUE THREAD

**Issue by McTristan** [wubbl0rz/FiatChamp#8] opened 2022-10-16 09:02 UTC
I've tried everything now but although I get the add on running, it does not create any sensors, devices etc.

My log says the following:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
===== CONFIG ===== 
{
  "FiatUser": "heregoesmyusername",
  "FiatPw": "********",
  "FiatPin": "****",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "****************************************************************",
  "RefreshInterval": 15,
  "AutoRefreshLocation": true,
  "AutoRefreshBattery": true,
  "EnableDangerousCommands": false,
  "DevMode": false
}
FETCH DATA... 10/16/2022 10:47:54
SEND COMMAND: DEEPREFRESH
COMMAND: DEEPREFRESH SUCCESSFUL
SEND COMMAND: VF
COMMAND: VF SUCCESSFUL
REFRESH SESSION
REFRESH SESSION
REFRESH SESSION
REFRESH SESSION
```

I've reinstalled the add-on already, restarted home assistant over and over again -> nothing. My home assistant is the native home assistant image running on a raspberry pi. I'm using version 2022.10.4.

**Comment by kduchrow** [comment] 2022-10-16 09:42
This sounds like you have not installed or started the Mosquito AddOn in advance.
Have a look at the Prerequisites and make sure, the MQTT Addon is up and running

> Prerequisites
- Official Home Assistant MQTT Addon up and running.

[Readme](https://github.com/wubbl0rz/FiatChamp)

**Comment by McTristan** [comment] 2022-10-16 09:46
The MQTT Broker is running:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[10:31:58] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:31:59] INFO: Starting NGINX for authentication handling...
[10:31:59] INFO: Starting mosquitto MQTT broker...
2022-10-16 10:31:59: Warning: Mosquitto should not be run as root/administrator.
[10:32:01] INFO: Successfully send discovery information to Home Assistant.
[10:32:01] INFO: Successfully send service information to the Supervisor.
2022-10-16 10:31:59: mosquitto version 2.0.11 starting
2022-10-16 10:31:59: Config loaded from /etc/mosquitto/mosquitto.conf.
2022-10-16 10:31:59: Loading plugin: /usr/share/mosquitto/go-auth.so
2022-10-16 10:31:59:  ├── Username/password checking enabled.
2022-10-16 10:31:59:  ├── TLS-PSK checking enabled.
2022-10-16 10:31:59:  └── Extended authentication not enabled.
2022-10-16 10:31:59: Opening ipv4 listen socket on port 1883.
2022-10-16 10:31:59: Opening ipv6 listen socket on port 1883.
2022-10-16 10:31:59: Opening websockets listen socket on port 1884.
2022-10-16 10:31:59: mosquitto version 2.0.11 running
2022-10-16 10:32:00: New connection from 127.0.0.1:52288 on port 1883.
2022-10-16 10:32:00: Client <unknown> closed its connection.
2022-10-16 10:32:34: New connection from 172.30.33.5:46864 on port 1883.
2022-10-16 10:32:34: New client connected from 172.30.33.5:46864 as FiatChamp (p2, c1, k15, u'addons').
2022-10-16 10:32:38: New connection from 172.30.32.2:32906 on port 1883.
2022-10-16 10:32:38: Client <unknown> closed its connection.
2022-10-16 10:34:38: New connection from 172.30.32.2:47770 on port 1883.
2022-10-16 10:34:38: Client <unknown> closed its connection.
2022-10-16 10:36:38: New connection from 172.30.32.2:55476 on port 1883.
2022-10-16 10:36:38: Client <unknown> closed its connection.
2022-10-16 10:38:38: New connection from 172.30.32.2:35110 on port 1883.
2022-10-16 10:38:38: Client <unknown> closed its connection.
2022-10-16 10:40:38: New connection from 172.30.32.2:48824 on port 1883.
2022-10-16 10:40:38: Client <unknown> closed its connection.
2022-10-16 10:41:01: Client FiatChamp closed its connection.
2022-10-16 10:41:12: New connection from 172.30.33.5:46240 on port 1883.
2022-10-16 10:41:12: New client connected from 172.30.33.5:46240 as FiatChamp (p2, c1, k15, u'addons').
2022-10-16 10:41:33: Client FiatChamp closed its connection.
2022-10-16 10:41:44: New connection from 172.30.33.5:33152 on port 1883.
2022-10-16 10:41:44: New client connected from 172.30.33.5:33152 as FiatChamp (p2, c1, k15, u'addons').
2022-10-16 10:42:38: New connection from 172.30.32.2:41024 on port 1883.
2022-10-16 10:42:38: Client <unknown> closed its connection.
2022-10-16 10:44:38: New connection from 172.30.32.2:40184 on port 1883.
2022-10-16 10:44:38: Client <unknown> closed its connection.
2022-10-16 10:46:21: Client FiatChamp closed its connection.
2022-10-16 10:46:38: New connection from 172.30.32.2:57268 on port 1883.
2022-10-16 10:46:38: Client <unknown> closed its connection.
2022-10-16 10:47:54: New connection from 172.30.33.5:57062 on port 1883.
2022-10-16 10:47:54: New client connected from 172.30.33.5:57062 as FiatChamp (p2, c1, k15, u'addons').
2022-10-16 10:48:38: New connection from 172.30.32.2:60324 on port 1883.
2022-10-16 10:48:38: Client <unknown> closed its connection.
2022-10-16 10:50:38: New connection from 172.30.32.2:50816 on port 1883.
2022-10-16 10:50:38: Client <unknown> closed its connection.
2022-10-16 10:52:38: New connection from 172.30.32.2:37890 on port 1883.
2022-10-16 10:52:38: Client <unknown> closed its connection.
2022-10-16 10:54:38: New connection from 172.30.32.2:46412 on port 1883.
2022-10-16 10:54:38: Client <unknown> closed its connection.
2022-10-16 10:56:38: New connection from 172.30.32.2:38110 on port 1883.
2022-10-16 10:56:38: Client <unknown> closed its connection.
2022-10-16 10:58:38: New connection from 172.30.32.2:43680 on port 1883.
2022-10-16 10:58:38: Client <unknown> closed its connection.
2022-10-16 11:00:38: New connection from 172.30.32.2:36674 on port 1883.
2022-10-16 11:00:38: Client <unknown> closed its connection.
2022-10-16 11:02:01: Saving in-memory database to /data//mosquitto.db.
2022-10-16 11:02:38: New connection from 172.30.32.2:54546 on port 1883.
2022-10-16 11:02:38: Client <unknown> closed its connection.
2022-10-16 11:04:38: New connection from 172.30.32.2:40008 on port 1883.
2022-10-16 11:04:38: Client <unknown> closed its connection.
2022-10-16 11:06:38: New connection from 172.30.32.2:34838 on port 1883.
```

**Comment by kduchrow** [comment] 2022-10-16 10:03
Have you configured the new MQTT Integration in the Homeassistant Integrations? 
It should look like this: 
![image](https://user-images.githubusercontent.com/25195144/196029438-c29509be-4862-4c9a-9ea4-98079808aa86.png)

**Comment by McTristan** [comment] 2022-10-16 10:06
yes but with another broker

**Comment by bigstevehardy** [comment] 2022-10-16 10:10
I used the mosquito broker and it worked perfectly, perhaps try going with that one ? App is amazing !!! saves me using the rubbish fiat app

**Comment by McTristan** [comment] 2022-10-16 10:11
As I mentioned I can use the MQTT integration only with one broker, as I have many entities "hanging" on this external broker I can't simply switch (without changing all other parts of my IoT-network).

**Comment by McTristan** [comment] 2022-10-16 10:13
maybe an "advanced" configuration for the mqtt settings could help me? I.e. if I would be able to specify the broker settings within the add-on configuration.

**Comment by McTristan** [comment] 2022-10-16 10:57
I worked around the issue by using the local broker only and forwarding all my relevant message topics to this broker. It's a bit cumbersome but it seems to work. Would be great if one could configure own MQTT settings.

**Comment by wubbl0rz** [comment] 2022-10-16 11:05
yes i can add some manual mqtt configuration. sounds like a good idea. it can keep the default behavior and only if mqtt config is overwritten in the settings it will use the external broker. but first i do the km -> miles conversion in the other issue. 😄

**Comment by wubbl0rz** [comment] 2022-10-16 13:56
after implementing this maybe i can drop the 

```
services:
   - "mqtt:need"
```
in the config too. but first need to check if the build in discovery of mqtt credentials and server will still work. no need to force users to install the mqtt addon if they do not use it :smile:

**Comment by wubbl0rz** [comment] 2022-10-16 15:16
please try again with 2.0.14. @McTristan 

# CHANGELOG

## 2.0.14 - 2022-10-16
- override mqtt option. only use this if you want to utilize an external mqtt broker.
  you do not need this if you are using the official home assistant mqtt addon.
- official mqtt addon no longer hardcoded required to start the addon. but its still the recommended way of using this addon.
- more mqtt logging

![image](https://user-images.githubusercontent.com/30373916/196043378-fcb067c0-89bc-4b75-95cf-bb930199430e.png)

**Comment by McTristan** [comment] 2022-10-16 16:48
Works! I can see all the new topics inside the EMQX dashboard (my mqtt broker). I just wish (in general), initial fetching of the values would work right after start up of the add-on - currently it seems it starts only after the specified refresh time for the first time (and then repeats fetching every X minutes). As all the sensor states are undefined by default that looks a bit weird on my dashboard for a couple of minutes.

**Comment by wubbl0rz** [comment] 2022-10-16 16:56
it should do exactly that 😄 first announce sensor and then publish the value.

![image](https://user-images.githubusercontent.com/30373916/196047851-1ed908de-251b-4ac3-a1da-adabd5b7accc.png)

i think the problem is home assistant have to know the sensor before it can receive data for it. so if the addon announces a new sensor and pushes the value too fast then home assistant has not created the sensor yet. i had the same problem and i put a 200ms sleep inside the announce call. but maybe that 200ms delay is not sufficient if all is sent over an external broker. maybe we could try a 500ms delay if an external broker is configured. or make the delay a config option. but the addon already has a lot of options on the config page 😅

**Comment by wubbl0rz** [comment] 2022-10-19 13:18
dashboard issue should be fixed now. i added a 5 sec delay between add all sensors and pushing values for them. 

# CHANGELOG

## 2.0.15 - 2022-10-19
- fix location sensor status.
- zone support. car location sensor now shows correct zone as defined in home assistant if car is in a 1000m radius of the zone. 
- autodetect from home assistant config if km -> miles conversion is needed. force conversion option still available.
- if using km -> miles conversion. rounded miles to .2 digits.
- 5sec delay between adding new sensors and pushing values to home assistant.

**Closed by wubbl0rz** 2022-10-19 13:18 UTC
Labels: enhancement
